'use strict';

/**
 * Deletion advice.
 *
 * Every file the scanner sees gets one verdict:
 *
 *   safe      regenerable junk -- deleting it costs nothing but disk churn
 *   review    big or long-untouched -- plausibly deletable, but only you know
 *   protected refused by the delete guards; shown so you know why
 *   keep      everything else (default). Never suggested for deletion.
 *
 * Classification has to run on every file of a 500k-file scan, so the
 * expensive part -- deciding what a directory *is* -- happens once per
 * directory and is inherited by everything beneath it. Per file the work is an
 * extension lookup and at most two string tests.
 */

const path = require('node:path');
const { isProtectedPath, extOf } = require('./util');
const { message: m } = require('../../i18n');

const DAY = 24 * 60 * 60 * 1000;

const THRESHOLDS = {
  staleDays: 180, // "you have not opened this in half a year"
  largeBytes: 100 * 1024 * 1024, // 100 MB before a file is worth reviewing
  installerDays: 30, // an installer older than this has served its purpose
  logDays: 7, // keep recent logs, they may still be useful
  archiveBytes: 50 * 1024 * 1024,
};

const CATEGORIES = {
  temp: {
    verdict: 'safe',
    label: 'Temporary files',
    hint: 'Left behind by apps that never cleaned up after themselves.',
  },
  cache: {
    verdict: 'safe',
    label: 'Caches',
    hint: 'Rebuilt automatically the next time the app needs them.',
  },
  crashdump: {
    verdict: 'safe',
    label: 'Crash dumps',
    hint: 'Diagnostic snapshots from programs that crashed. Only useful to a developer debugging that crash.',
  },
  log: {
    verdict: 'safe',
    label: 'Old log files',
    hint: 'Diagnostic logs older than a week.',
  },
  buildoutput: {
    verdict: 'safe',
    label: 'Build output',
    hint: 'Regenerated by rebuilding the project. Source code is untouched.',
  },
  installer: {
    verdict: 'review',
    label: 'Old installers',
    hint: 'Setup files you already ran. Re-downloadable, but that costs bandwidth.',
  },
  archive: {
    verdict: 'review',
    label: 'Large archives & disk images',
    hint: 'Check each one — an archive or VM disk may be the only copy of what is inside it.',
  },
  gpucache: {
    verdict: 'safe',
    label: 'GPU & compiled-code caches',
    hint: 'Shader and bytecode artifacts. Every Chromium-based app regenerates these on next launch.',
  },
  appcache: {
    verdict: 'review',
    label: 'Application caches',
    hint: 'Caches belonging to installed programs. Usually rebuilt — but only that program knows what it keeps here, so nothing here is selected for you.',
  },
  stale: {
    verdict: 'review',
    label: 'Large & untouched',
    hint: 'Big files you have not opened in a long time. Nothing here is junk by itself.',
  },
};

const VERDICT_ORDER = { safe: 0, review: 1, protected: 2, keep: 3 };

/* -------------------------------------------------------------------------- */
/* directory tagging -- runs once per directory                                */
/* -------------------------------------------------------------------------- */

// Exact directory names that mark everything beneath them, wherever they sit.
//
// `gpucache` is kept separate from `cache` on purpose. GPU, shader and compiled
// -code caches are machine-generated artifacts that every Chromium build
// regenerates on next launch. A directory merely called "Cache" is not that
// reliable -- it is whatever the application decided to put there.
const DIR_TAGS = new Map(
  Object.entries({
    temp: 'temp',
    tmp: 'temp',
    cache: 'cache',
    caches: 'cache',
    cachestorage: 'cache',
    cache_data: 'cache',
    'code cache': 'gpucache',
    gpucache: 'gpucache',
    dawncache: 'gpucache',
    dawngraphitecache: 'gpucache',
    dawnwebgpucache: 'gpucache',
    shadercache: 'gpucache',
    grshadercache: 'gpucache',
    crashdumps: 'crashdump',
    minidump: 'crashdump',
    crashpad: 'crashdump',
    logs: 'log',
    log: 'log',
    downloads: 'downloads',

    // Live application state. Nothing under these is ever disposable, whatever
    // it is named -- Chromium's Local Storage is a LevelDB whose write-ahead
    // log is literally called `000003.log`, which the log rule would otherwise
    // classify as an old log file and delete.
    'local storage': 'userdata',
    'session storage': 'userdata',
    indexeddb: 'userdata',
    leveldb: 'userdata',
    databases: 'userdata',
    'service worker': 'userdata',
    'local state': 'userdata',
    network: 'userdata',
    blob_storage: 'userdata',
    webstorage: 'userdata',
    'shared proto db': 'userdata',
  })
);

/** `https_example.com_0.indexeddb.leveldb` and friends. */
function isUserDataDirName(lower) {
  return lower.endsWith('.leveldb') || lower.endsWith('.indexeddb');
}

/**
 * Files an application's data directory is recognised by. Their presence means
 * "this folder is some program's live state", which switches the whole subtree
 * to the conservative rules.
 */
const APP_DATA_MARKERS = new Set([
  'local storage',
  'session storage',
  'indexeddb',
  'cookies',
  'cookies-journal',
  'preferences',
  'local state',
  'databases',
  'service worker',
  'leveldb',
  'network',
  'blob_storage',
  'webstorage',
  'settings.json',
  'config.json',
  'user.config',
]);

/**
 * Is this directory an application's data/profile folder?
 *
 * Recognised from the listing the walk already holds, so it costs no syscalls
 * and -- unlike a list of known apps -- it works for software that was never
 * heard of when this was written.
 */
function looksLikeAppData(entries) {
  for (const entry of entries) {
    const lower = entry.name.toLowerCase();
    if (APP_DATA_MARKERS.has(lower)) return true;
    if (entry.isFile() && (lower.endsWith('.sqlite') || lower.endsWith('.sqlite3'))) return true;
  }
  return false;
}

/**
 * Build-output names are far too generic to trust on their own -- `bin` is a
 * compiler's output directory inside a project and an installed program's
 * executables everywhere else. These only count when the *parent* directory
 * looks like a source project.
 */
const BUILD_DIR_NAMES = new Set(['obj', 'bin', 'dist', 'build', 'target', 'out']);

/** Files whose presence means "this directory is a source project". */
const PROJECT_MARKERS = new Set([
  'package.json',
  'cargo.toml',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'build.gradle.kts',
  'makefile',
  'cmakelists.txt',
  'pyproject.toml',
  'composer.json',
  'gemfile',
  'build.sbt',
  'mix.exs',
]);

const PROJECT_MARKER_SUFFIXES = ['.csproj', '.sln', '.fsproj', '.vbproj', '.vcxproj'];

/**
 * Does this directory hold an installed application?
 *
 * This exists because of a real breakage: VS Code ships
 * `resources\app\package.json`, which made `looksLikeProject` true, which made
 * the sibling `out\` match the build-output rule -- so the editor's entire
 * compiled JavaScript was offered as "safe to delete". An application's
 * `out\` is its product, not rebuildable scratch.
 *
 * Detected from the listing the walk already has: an uninstaller, or an
 * executable sitting next to the `resources`/`locales`/`app` layout that
 * packaged apps use.
 *
 * @param {Array<{name: string, isFile: () => boolean, isDirectory: () => boolean}>} entries
 */
function looksLikeInstalledApp(entries) {
  let hasExecutable = false;
  let hasAppLayout = false;

  for (const entry of entries) {
    const lower = entry.name.toLowerCase();

    if (entry.isFile()) {
      if (/^unins.*\.exe$/.test(lower) || /^uninstall.*\.exe$/.test(lower)) return true;
      if (lower.endsWith('.exe')) hasExecutable = true;
      continue;
    }
    if (entry.isDirectory() && (lower === 'resources' || lower === 'locales')) {
      hasAppLayout = true;
    }
  }

  return hasExecutable && hasAppLayout;
}

/**
 * Does this directory listing belong to a source project? Called once per
 * directory with the entries the walk has already read, so it costs no extra
 * syscalls.
 *
 * @param {Array<{name: string, isFile: () => boolean}>} entries
 */
function looksLikeProject(entries) {
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const lower = entry.name.toLowerCase();
    if (PROJECT_MARKERS.has(lower)) return true;
    for (const suffix of PROJECT_MARKER_SUFFIXES) {
      if (lower.endsWith(suffix)) return true;
    }
  }
  return false;
}

/**
 * Tag for a directory. A tag, once applied, is inherited by every
 * subdirectory beneath it.
 *
 * @param {string} name             directory basename
 * @param {string|null} parentTag   tag inherited from the parent
 * @param {boolean} parentIsProject whether the parent holds a project marker
 * @returns {string|null}
 */
function tagDirectory(name, parentTag, parentIsProject = false) {
  if (parentTag) return parentTag;

  const lower = name.toLowerCase();
  if (isUserDataDirName(lower)) return 'userdata';
  const tag = DIR_TAGS.get(lower);
  if (tag) return tag;

  if (parentIsProject && BUILD_DIR_NAMES.has(lower)) return 'buildoutput';
  return null;
}

/* -------------------------------------------------------------------------- */
/* file classification -- runs once per file                                   */
/* -------------------------------------------------------------------------- */

const EXT_CATEGORY = new Map(
  Object.entries({
    tmp: 'temp',
    temp: 'temp',
    partial: 'temp',
    crdownload: 'temp',
    part: 'temp',
    download: 'temp',
    bak: 'temp',
    dmp: 'crashdump',
    mdmp: 'crashdump',
    hdmp: 'crashdump',
    log: 'log',
  })
);

const INSTALLER_EXT = new Set(['exe', 'msi', 'msix', 'appx', 'dmg', 'pkg', 'deb', 'rpm']);
const ARCHIVE_EXT = new Set([
  'zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz', 'iso', 'img',
  'vhd', 'vhdx', 'vmdk', 'vdi', 'qcow2', 'wim', 'esd',
]);

/**
 * Decide what to advise about one file.
 *
 * @param {object} file  { name, ext, size, mtimeMs, atimeMs }
 * @param {string|null} dirTag  tag inherited from the containing directory
 * @param {number} now   timestamp the ages are measured against
 * @returns {{category: string, verdict: string, reason: string} | null}
 *          null means "keep" -- nothing to say about this file.
 */
function classifyFile(file, dirTag, now, blockKind = 'none') {
  const raw = classifyRaw(file, dirTag, now);
  return gate(raw, blockKind);
}

/**
 * Narrow a verdict to what is defensible where the file actually lives.
 *
 *   'none'  ordinary user territory -- the rules stand as written
 *   'app'   inside some program's data folder: only machine-generated GPU and
 *           crash artifacts may be called safe, and file-name rules are off
 *           entirely, because a name means whatever that program decided
 *   'hard'  inside an installed application or roaming data: nothing is safe
 *
 * Review verdicts always survive -- they are shown, explained, and never
 * selected for you.
 */
function gate(result, blockKind) {
  if (!result || blockKind === 'none') return result;
  if (result.verdict !== 'safe') return result;
  if (blockKind === 'hard') return null;

  // Inside app data. Only directory-derived, machine-generated artifacts.
  if (result.source !== 'dir') return null;
  if (SAFE_INSIDE_APP_DATA.has(result.category)) return result;

  return {
    category: 'appcache',
    verdict: 'review',
    source: result.source,
    reason: m(
      'reason.appcache',
      'A cache belonging to an installed program. Usually rebuilt, but only that program knows what ' +
        'it keeps here — check before removing it.'
    ),
  };
}

/** Categories that stay safe even inside an application's own data folder. */
const SAFE_INSIDE_APP_DATA = new Set(['gpucache', 'crashdump']);

function classifyRaw(file, dirTag, now) {
  const { name, ext, size, mtimeMs } = file;
  // Prefer access time, but fall back to mtime wherever the filesystem does
  // not maintain one (see accessTimesAreTracked).
  const lastTouched = file.atimeMs || mtimeMs;
  const ageDays = (now - lastTouched) / DAY;
  const modifiedDays = (now - mtimeMs) / DAY;

  /* -- live application state: never anything ----------------------------- */
  if (dirTag === 'userdata') return null;

  /* -- Office / editor lock files: always junk, any size ------------------ */
  if (name.startsWith('~$') || name.startsWith('.~lock.')) {
    return advice('temp', m('reason.lockFile', 'Editor lock file from a document that is no longer open'), 'name');
  }

  /* -- inherited directory context --------------------------------------- */
  if (dirTag && dirTag !== 'downloads') {
    if (dirTag === 'log') return logAdvice(modifiedDays, 'dir');
    return advice(dirTag, DIR_REASON[dirTag], 'dir');
  }

  /* -- extension-driven --------------------------------------------------- */
  const byExt = EXT_CATEGORY.get(ext);
  if (byExt) {
    if (byExt === 'log') return logAdvice(modifiedDays, 'ext');
    return advice(byExt, EXT_REASON[byExt], 'ext');
  }

  /* -- installers sitting in Downloads ------------------------------------ */
  if (dirTag === 'downloads' && INSTALLER_EXT.has(ext) && modifiedDays >= THRESHOLDS.installerDays) {
    const age = ageParts(modifiedDays);
    return advice('installer', m(`reason.installer.${age.unit}`, INSTALLER_EN[age.unit], { n: age.value }), 'ext');
  }

  /* -- big archives and VM disks ------------------------------------------ */
  if (ARCHIVE_EXT.has(ext) && size >= THRESHOLDS.archiveBytes) {
    if (ageDays >= THRESHOLDS.staleDays) {
      const age = ageParts(ageDays);
      return advice('archive', m(`reason.archiveStale.${age.unit}`, ARCHIVE_EN[age.unit], { n: age.value }), 'ext');
    }
    return advice(
      'archive',
      m('reason.archive', 'Check the contents are stored elsewhere before deleting'),
      'ext'
    );
  }

  /* -- large and untouched ------------------------------------------------- */
  if (size >= THRESHOLDS.largeBytes && ageDays >= THRESHOLDS.staleDays) {
    const age = ageParts(ageDays);
    return advice('stale', m(`reason.stale.${age.unit}`, STALE_EN[age.unit], { n: age.value }), 'size');
  }

  return null;
}

const DIR_REASON = {
  temp: m('reason.dir.temp', 'Inside a temporary folder'),
  cache: m('reason.dir.cache', 'Inside a cache folder — the app rebuilds it on demand'),
  gpucache: m('reason.dir.gpucache', 'GPU or compiled-code cache — regenerated on next launch'),
  crashdump: m('reason.dir.crashdump', 'Crash dump left by a program that stopped responding'),
  log: m('reason.dir.log', 'Old log file'),
  buildoutput: m('reason.dir.buildoutput', 'Build output — recreated by rebuilding the project'),
};

const EXT_REASON = {
  temp: m('reason.ext.temp', 'Temporary or partially-downloaded file'),
  crashdump: m('reason.ext.crashdump', 'Crash dump from a program that stopped responding'),
  log: m('reason.ext.log', 'Old log file'),
};

/*
 * Ages, as a number and a unit rather than a sentence.
 *
 * `formatAge` used to return "3 months" and the reasons interpolated it. That
 * cannot be translated: the unit would stay English inside a Vietnamese
 * sentence, and Vietnamese does not put it where English does anyway. So the
 * unit selects the key and the number is the parameter, which lets each
 * language write the whole sentence its own way.
 */
const AGE_UNITS = ['years', 'months', 'days', 'recent'];

function ageParts(days) {
  if (days >= 365) {
    const years = days / 365;
    return { unit: 'years', value: years < 2 ? Number(years.toFixed(1)) : Math.round(years) };
  }
  if (days >= 60) return { unit: 'months', value: Math.round(days / 30) };
  if (days >= 1) return { unit: 'days', value: Math.round(days) };
  return { unit: 'recent', value: 0 };
}

const STALE_EN = {
  years: 'Not opened in {n} years',
  months: 'Not opened in {n} months',
  days: 'Not opened in {n} days',
  recent: 'Not opened in the last day',
};

const ARCHIVE_EN = {
  years: 'Not opened in {n} years — check the contents are stored elsewhere first',
  months: 'Not opened in {n} months — check the contents are stored elsewhere first',
  days: 'Not opened in {n} days — check the contents are stored elsewhere first',
  recent: 'Check the contents are stored elsewhere before deleting',
};

const INSTALLER_EN = {
  years: 'Installer downloaded {n} years ago — the program it installs is unaffected by deleting it',
  months: 'Installer downloaded {n} months ago — the program it installs is unaffected by deleting it',
  days: 'Installer downloaded {n} days ago — the program it installs is unaffected by deleting it',
  recent: 'Installer downloaded today — the program it installs is unaffected by deleting it',
};

const LOG_EN = {
  years: 'Nothing written to it in {n} years',
  months: 'Nothing written to it in {n} months',
  days: 'Nothing written to it in {n} days',
  recent: 'Nothing written to it in the last day',
};

function advice(category, reason, source = 'dir') {
  return { category, verdict: CATEGORIES[category].verdict, reason, source };
}

/**
 * A log is judged on when it was last *written*, not last read -- indexers and
 * antivirus touch files constantly, so access time says nothing about whether
 * a log is still in use. The reason states the date the verdict came from.
 */
function logAdvice(modifiedDays, source) {
  if (modifiedDays < THRESHOLDS.logDays) return null;
  const age = ageParts(modifiedDays);
  return advice('log', m(`reason.log.${age.unit}`, LOG_EN[age.unit], { n: age.value }), source);
}

/**
 * The old sentence-producing version, kept for callers outside the advisor.
 *
 * Nothing in the app's own text goes through it any more -- see `ageParts` and
 * the *_EN tables above for why an age cannot be interpolated into a translated
 * sentence -- but it is exported, and a test reads it.
 */
function formatAge(days) {
  const { unit, value } = ageParts(days);
  if (unit === 'recent') return 'less than a day';
  const word = unit.slice(0, -1);
  return `${value} ${word}${value === 1 ? '' : 's'}`;
}

/* -------------------------------------------------------------------------- */
/* program components -- files that belong to installed software               */
/* -------------------------------------------------------------------------- */

/**
 * Dependency and runtime trees. Two projects each holding their own copy of the
 * same library is normal and correct -- the copies are not redundant, they are
 * per-environment. Deleting one breaks that environment.
 */
const DEPENDENCY_DIRS = new Set([
  'site-packages',
  'dist-packages',
  'node_modules',
  'venv',
  '.venv',
  'virtualenv',
  '.tox',
  'conda-meta',
  'vendor',
  'packages',
  'gems',
  'bower_components',
  'jspm_packages',
  '.gradle',
  '.nuget',
  '.cargo',
  'wheels',
]);

/**
 * Binaries loaded by other programs. Two copies almost always both matter --
 * each one is resolved from a different application's own directory.
 */
const BINARY_MODULE_EXT = new Set([
  'dll', 'pyd', 'so', 'dylib', 'sys', 'ocx', 'drv', 'ax', 'cpl',
  'node', 'jar', 'winmd', 'tlb', 'manifest', 'cat',
]);

/**
 * Why deleting this file is likely to break something, or null if it looks
 * like ordinary user data.
 *
 * Used by the duplicate finder: such files are still listed, but they are never
 * auto-selected by "select all but the oldest copy", because for program
 * components "duplicate" does not mean "redundant".
 *
 * @returns {string|null}
 */
function programComponentReason(filePath) {
  const segments = filePath.split(/[\\/]/);

  // Skip the filename itself; only directories carry this meaning.
  for (let i = 0; i < segments.length - 1; i++) {
    const segment = segments[i].toLowerCase();
    if (DEPENDENCY_DIRS.has(segment)) {
      return m('reason.dependency', 'Inside "{dir}" — each project needs its own copy of this', {
        dir: segments[i],
      });
    }
  }

  if (isProtectedPath(filePath)) {
    return m('reason.systemOwned', 'Belongs to the operating system or an installed program');
  }

  const ext = extOf(segments[segments.length - 1] || '');
  if (BINARY_MODULE_EXT.has(ext)) {
    return m('reason.binaryModule', 'A .{ext} loaded by some program — the copies are usually not interchangeable', {
      ext,
    });
  }

  return null;
}

/* -------------------------------------------------------------------------- */
/* accumulator                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Collects advice across a scan: totals per category plus the biggest
 * offenders in each, capped so a huge scan cannot exhaust memory.
 */
class Advisor {
  constructor({ now = Date.now(), keepPerCategory = 100 } = {}) {
    this.now = now;
    this.keep = keepPerCategory;
    this.buckets = new Map();
    this.protectedPaths = [];
    this.appFolders = [];
    this.appFolderKeys = new Set();
  }

  /** Record a folder whose contents are excluded from cleanup advice. */
  addAppFolder(dirPath, reason) {
    const key = dirPath.toLowerCase();
    if (this.appFolderKeys.has(key) || this.appFolders.length >= 200) return;
    this.appFolderKeys.add(key);
    this.appFolders.push({ path: dirPath, name: path.basename(dirPath), reason });
  }

  /**
   * @param {object} file
   * @param {string|null} dirTag
   * @param {boolean} blocked  inside an installed application or roaming app
   *   data, where nothing may be called "safe" no matter what it is named
   * @returns {object|null} the advice recorded, if any
   */
  add(file, dirTag, blockKind = 'none') {
    const result = classifyFile(file, dirTag, this.now, blockKind);
    if (!result) return null;

    let bucket = this.buckets.get(result.category);
    if (!bucket) {
      bucket = { category: result.category, bytes: 0, count: 0, files: [], overflow: false };
      this.buckets.set(result.category, bucket);
    }

    bucket.bytes += file.size;
    bucket.count++;
    bucket.files.push({
      path: file.path,
      size: file.size,
      mtimeMs: file.mtimeMs,
      atimeMs: file.atimeMs,
      reason: result.reason,
      // Which rule decided -- the folder, the extension, the name or the size.
      // The analyzer turns it into a confidence: a folder called Temp is
      // stronger evidence than a file that happens to end in .bak.
      source: result.source,
    });

    // Keep only the largest few; trim in batches rather than on every push.
    if (bucket.files.length >= this.keep * 4) this.trim(bucket);
    return result;
  }

  /** Record a location that was skipped because deleting it is not allowed. */
  addProtected(dirPath, reason) {
    if (this.protectedPaths.length < 200) {
      this.protectedPaths.push({ path: dirPath, name: path.basename(dirPath), reason });
    }
  }

  trim(bucket) {
    bucket.files.sort((a, b) => b.size - a.size);
    if (bucket.files.length > this.keep) {
      bucket.overflow = true;
      bucket.files.length = this.keep;
    }
  }

  /** Final report, sorted safe-first then by size reclaimed. */
  summary() {
    const groups = [...this.buckets.values()].map((bucket) => {
      this.trim(bucket);
      const meta = CATEGORIES[bucket.category];
      return {
        category: bucket.category,
        label: meta.label,
        hint: meta.hint,
        verdict: meta.verdict,
        bytes: bucket.bytes,
        count: bucket.count,
        files: bucket.files,
        truncated: bucket.overflow,
      };
    });

    groups.sort(
      (a, b) => VERDICT_ORDER[a.verdict] - VERDICT_ORDER[b.verdict] || b.bytes - a.bytes
    );

    const total = (verdict) =>
      groups.filter((g) => g.verdict === verdict).reduce((n, g) => n + g.bytes, 0);

    return {
      groups,
      safeBytes: total('safe'),
      reviewBytes: total('review'),
      protectedPaths: this.protectedPaths,
      appFolders: this.appFolders,
    };
  }
}

module.exports = {
  Advisor,
  tagDirectory,
  looksLikeProject,
  looksLikeInstalledApp,
  looksLikeAppData,
  programComponentReason,
  classifyFile,
  formatAge,
  CATEGORIES,
  THRESHOLDS,
  DAY,
};
