'use strict';

/**
 * The record of everything the app did to a file.
 *
 * One line of JSON per event, appended, never rewritten, in a file per month:
 *
 *   journal/2026-09.jsonl
 *   {"v":1,"t":"…","session":"s_8f2c","op":"begin","kind":"recycle","source":"manual","count":412,"bytes":…}
 *   {"v":1,"t":"…","session":"s_8f2c","op":"item","from":"C:\\…\\x.iso","to":null,"bytes":4700000000,"mtime":"…"}
 *   {"v":1,"t":"…","session":"s_8f2c","op":"end","done":410,"failed":1,"skipped":1,"movedBytes":…,"freedOnSource":0}
 *
 * ## Why append-only
 *
 * The file this replaces, `trash-ledger.json`, was rewritten whole on every
 * save from whatever copy the process had in memory. The window reads it once
 * at launch; the 02:00 cleanup is a separate process that writes to it. So a
 * window left open overnight, asked to delete something the next morning,
 * wrote back its own stale copy plus the new entries -- and the scheduled run's
 * entries were gone. Nothing broke loudly: those items were simply never
 * purged, because the record that they were ours had been overwritten.
 *
 * An append cannot lose somebody else's line. Two processes appending to the
 * same file interleave whole lines, and `scripts/test-journal.js` measures
 * that rather than assuming it.
 *
 * ## What is in a line
 *
 * An `item` line is written after the action succeeded and before the window
 * is told, so a process that dies half way leaves a journal that is exactly
 * what happened. Every destination path in it was generated by the app, never
 * read out of a file. Readers ignore fields they do not know.
 *
 * ## Sealed, when it is given a sealer (H4)
 *
 * Then each line also carries `prev`, the hash of the line before it in the
 * same session, and each session ends with a signed `seal` line; `seal.js`
 * says why the chain runs per session and not per file. Whether there is a
 * sealer is decided by whoever builds the journal (`services.js`), from the
 * licence. This file never asks: everything that reads the journal must work
 * whatever the licence says, and a sealed journal and an unsealed one read
 * the same to every reader but the check.
 */

const crypto = require('node:crypto');
const fsp = require('node:fs/promises');
const path = require('node:path');

const { ACTION_KINDS } = require('../analyzers/contract');
const { hashLine, rangesOf } = require('./seal');

const VERSION = 1;

/**
 * How long a month's file is kept. Thirteen months, so a purge grace period at
 * its maximum of a year still finds the record of what it is purging.
 */
const KEEP_MONTHS = 13;

/**
 * The kinds a session may be: the contract's actions, plus two that act on the
 * app's own earlier sessions rather than on a candidate -- the purge, which
 * removes what the app put in the bin, and the restore, which puts it back.
 * Both name each item with the moment it was first recycled (`recycledAt`),
 * which is how the ledger knows those items are no longer the app's to purge.
 */
const KINDS = new Set([...ACTION_KINDS, 'purge', 'restore']);

function monthOf(ms) {
  const d = new Date(ms);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
}

const iso = (ms) => (Number.isFinite(ms) ? new Date(ms).toISOString() : null);

class ActionJournal {
  /**
   * @param {string} dir
   * @param {object} [options]
   * @param {() => number} [options.now]   injectable clock, for the harnesses
   * @param {import('./seal').Sealer|null} [options.sealer]   seals each session (H4); none, none
   */
  constructor(dir, { now = Date.now, keepMonths = KEEP_MONTHS, sealer = null } = {}) {
    this.dir = path.resolve(dir);
    this.now = now;
    this.keepMonths = keepMonths;
    this.sealer = sealer;
    this._ready = null;
    // Per open session: the hash its next line names, how many lines it has,
    // and the queue its appends go through. Kept off the session object, which
    // callers pass about and some of them log.
    this._open = new WeakMap();
  }

  fileFor(ms) {
    return path.join(this.dir, `${monthOf(ms)}.jsonl`);
  }

  async _ensureDir() {
    if (!this._ready) this._ready = fsp.mkdir(this.dir, { recursive: true }).then(() => true);
    return this._ready;
  }

  /** One write per call, so a line is never split across two appends. */
  async _appendTexts(file, texts) {
    await this._ensureDir();
    await fsp.appendFile(file, texts.map((text) => `${text}\n`).join(''), 'utf8');
  }

  /**
   * Seal the sessions that begin from now on, or stop sealing them.
   *
   * The licence can change while the app runs (Phase 6), and whoever builds
   * the journal hands it the new answer here -- the journal still never asks.
   * A session keeps the sealer it began with, so none is ever half chained.
   */
  useSealer(sealer) {
    this.sealer = sealer || null;
  }

  _stateOf(session) {
    let state = this._open.get(session);
    if (!state) {
      state = { head: null, count: 0, queue: Promise.resolve(), sealer: this.sealer };
      this._open.set(session, state);
    }
    return state;
  }

  /**
   * One session's appends, one after another and in the order they were
   * asked for -- so its lines stand in the file in the order they happened,
   * and the chain is built in that order too. A failed append does not stop
   * the next; it leaves the gap it leaves, and the check reports it.
   */
  _enqueue(session, task) {
    const state = this._stateOf(session);
    const run = state.queue.catch(() => {}).then(task);
    state.queue = run;
    return run;
  }

  /** The lines as text, chained when sealing. `prev` of a session's first line is null. */
  _chain(state, lines) {
    let { head, count } = state;
    const texts = lines.map((line) => {
      if (state.sealer) line.prev = head;
      const text = JSON.stringify(line);
      if (state.sealer) {
        head = hashLine(text);
        count += 1;
      }
      return text;
    });
    return { texts, head, count };
  }

  async _write(session, lines) {
    const state = this._stateOf(session);
    const { texts, head, count } = this._chain(state, lines);
    await this._appendTexts(session.file, texts);
    // Moved on only once the line is on disk: a line that failed to write is
    // not one the next line may claim to follow.
    state.head = head;
    state.count = count;
  }

  /**
   * A session's last lines, and its seal in the same append.
   *
   * When the seal cannot be made -- the lock held too long, PowerShell refused,
   * the key would not open -- the lines are written all the same. The record
   * of what happened to somebody's files comes first; the seal on it second.
   */
  async _finish(session, lines) {
    const state = this._stateOf(session);
    if (!state.sealer) return this._write(session, lines);
    let ticket = null;
    try {
      ticket = await state.sealer.open((isGenuine) => this._lastSeal(isGenuine));
      this.sealError = null;
    } catch (err) {
      this.sealError = err;
    }
    try {
      const { texts, head, count } = this._chain(state, lines);
      if (ticket) {
        texts.push(JSON.stringify(ticket.seal({ session: session.id, prev: head, lines: count, t: iso(this.now()) })));
      }
      await this._appendTexts(session.file, texts);
      state.head = head;
      state.count = count;
    } finally {
      if (ticket) await ticket.close();
    }
  }

  /**
   * The newest seal that checks, so the next one can number itself after it.
   *
   * Read from the month files every time, with the lock held, rather than
   * from a note kept beside them: a note and the journal can disagree after a
   * crash between the two writes, and then two seals carry the same number.
   * Only lines that mention a seal are parsed, newest number first, and the
   * signature is checked until one holds -- normally the first.
   */
  async _lastSeal(isGenuine) {
    const candidates = [];
    for (const file of await this.files()) {
      let text;
      try {
        text = await fsp.readFile(file, 'utf8');
      } catch {
        continue;
      }
      if (!text.includes('"seal"')) continue;
      for (const raw of text.split('\n')) {
        if (!raw.includes('"seal"')) continue;
        try {
          const line = JSON.parse(raw);
          if (line && line.op === 'seal' && Number.isInteger(line.n) && line.n > 0) candidates.push({ line, raw });
        } catch {
          // not a line at all
        }
      }
    }
    candidates.sort((a, b) => b.line.n - a.line.n);
    const found = candidates.find((c) => isGenuine(c.line));
    return found ? { n: found.line.n, hash: hashLine(found.raw) } : { n: 0, hash: null };
  }

  /**
   * Open a session. Its lines all go to the file of the month it began in, so
   * a session that runs across midnight at the end of a month is still one
   * file's worth of reading.
   */
  async begin(kind, description = {}, { source = 'manual', runId = null } = {}) {
    if (!KINDS.has(kind)) throw new Error(`journal: "${kind}" is not an action kind`);
    const startedAt = this.now();
    const session = {
      id: `s_${crypto.randomBytes(4).toString('hex')}`,
      kind,
      file: this.fileFor(startedAt),
      startedAt,
    };
    await this._enqueue(session, () =>
      this._write(session, [
        {
          v: VERSION,
          t: iso(startedAt),
          session: session.id,
          op: 'begin',
          kind,
          source,
          runId,
          count: description.count || 0,
          bytes: description.bytes || 0,
          freesOnVolume: Boolean(description.freesOnVolume),
          reversible: description.reversible || null,
        },
      ])
    );
    return session;
  }

  /** One item that has already happened. */
  async record(session, item) {
    if (!session) return;
    const line = this._itemLine(session, item);
    await this._enqueue(session, () => this._write(session, [line]));
  }

  _itemLine(session, item) {
    return {
      v: VERSION,
      t: iso(Number.isFinite(item.trashedAt) ? item.trashedAt : this.now()),
      session: session.id,
      op: 'item',
      // A handoff's item is what was opened -- `ms-settings:storagesense` or a
      // program with its arguments -- not a path to resolve.
      from: session.kind === 'handoff' ? String(item.path) : path.resolve(item.path),
      to: item.to || null,
      bytes: Number.isFinite(item.size) ? item.size : 0,
      mtime: iso(item.mtimeMs),
      // Only on a purge: when the item it removes was first recycled, which is
      // how the two records are matched up.
      ...(Number.isFinite(item.recycledAt) ? { recycledAt: iso(item.recycledAt) } : {}),
      // Only on a quarantine (B1): what the copy was checked against, and where
      // the original went -- `bin`, which the purge may later empty, or
      // `deleted`, which nothing can.
      ...(typeof item.sha256 === 'string' && /^[0-9a-f]{64}$/.test(item.sha256) ? { sha256: item.sha256 } : {}),
      ...(item.original === 'bin' || item.original === 'deleted' ? { original: item.original } : {}),
    };
  }

  async end(session, result = {}) {
    if (!session) return;
    const line = {
      v: VERSION,
      t: iso(this.now()),
      session: session.id,
      op: 'end',
      done: result.done || 0,
      failed: result.failed || 0,
      skipped: result.skipped || 0,
      cancelled: Boolean(result.cancelled),
      movedBytes: result.movedBytes || 0,
      freedOnSource: result.freedOnSource || 0,
      error: result.error || null,
    };
    await this._enqueue(session, () => this._finish(session, [line]));
  }

  /**
   * A whole session in one write: for records made after the fact -- the
   * import of the old ledger, and a purge.
   */
  async appendSession(kind, items, { source = 'manual', runId = null, startedAt, freedOnSource = 0 } = {}) {
    if (!KINDS.has(kind)) throw new Error(`journal: "${kind}" is not an action kind`);
    const at = Number.isFinite(startedAt) ? startedAt : this.now();
    const session = { id: `s_${crypto.randomBytes(4).toString('hex')}`, kind, file: this.fileFor(this.now()), startedAt: at };
    const bytes = items.reduce((n, item) => n + (Number.isFinite(item.size) ? item.size : 0), 0);
    const lines = [
      { v: VERSION, t: iso(at), session: session.id, op: 'begin', kind, source, runId, count: items.length, bytes },
      ...items.map((item) => this._itemLine(session, item)),
      {
        v: VERSION,
        t: iso(this.now()),
        session: session.id,
        op: 'end',
        done: items.length,
        failed: 0,
        skipped: 0,
        cancelled: false,
        movedBytes: kind === 'purge' ? 0 : bytes,
        freedOnSource,
        error: null,
      },
    ];
    await this._finish(session, lines);
    return session;
  }

  /** The month files present, oldest first. */
  async files() {
    let names;
    try {
      names = await fsp.readdir(this.dir);
    } catch {
      return [];
    }
    return names
      .filter((name) => /^\d{4}-\d{2}\.jsonl$/.test(name))
      .sort()
      .map((name) => path.join(this.dir, name));
  }

  /**
   * Every line, oldest file first. A line that does not parse -- a torn write
   * after a power cut, a hand edit -- is skipped and counted, never fatal: the
   * journal is read by a scheduled task that must not stop over one bad line.
   *
   * @returns {Promise<{lines: object[], malformed: number}>}
   */
  async read() {
    const lines = [];
    let malformed = 0;
    for (const file of await this.files()) {
      let text;
      try {
        text = await fsp.readFile(file, 'utf8');
      } catch {
        continue;
      }
      for (const raw of text.split('\n')) {
        if (raw.trim() === '') continue;
        let line;
        try {
          line = JSON.parse(raw);
        } catch {
          malformed += 1;
          continue;
        }
        if (!line || typeof line.session !== 'string' || typeof line.op !== 'string') {
          malformed += 1;
          continue;
        }
        lines.push(line);
      }
    }
    return { lines, malformed };
  }

  /**
   * Sessions, newest first, each with its items -- what the Restore Center
   * will list. A session with a `begin` and no `end` is reported as
   * incomplete: the process died while it was running.
   */
  async sessions() {
    const { lines } = await this.read();
    const byId = new Map();
    for (const line of lines) {
      let s = byId.get(line.session);
      if (!s) {
        s = { id: line.session, kind: null, source: null, runId: null, startedAt: null, endedAt: null, items: [], end: null };
        byId.set(line.session, s);
      }
      if (line.op === 'begin') {
        s.kind = line.kind;
        s.source = line.source || null;
        s.runId = line.runId || null;
        s.startedAt = Date.parse(line.t);
        s.count = line.count || 0;
        s.bytes = line.bytes || 0;
        s.freesOnVolume = Boolean(line.freesOnVolume);
      } else if (line.op === 'item') {
        s.items.push(line);
      } else if (line.op === 'end') {
        s.endedAt = Date.parse(line.t);
        s.end = line;
      }
    }
    return [...byId.values()]
      .filter((s) => s.kind)
      .map((s) => ({ ...s, complete: s.end !== null }))
      .sort((a, b) => b.startedAt - a.startedAt);
  }

  /**
   * Drop month files older than the retention -- this month and the twelve
   * before it, by default. Whole files only; a line is never edited.
   *
   * Except a month that holds a quarantine (B1). Its copies stay on the other
   * drive for as long as somebody leaves them there, which the app never
   * decides, and the journal is how the Restore Center knows where each one
   * came from.
   */
  async prune() {
    const cutoff = new Date(this.now());
    cutoff.setUTCDate(1);
    cutoff.setUTCMonth(cutoff.getUTCMonth() - (this.keepMonths - 1));
    const oldest = monthOf(cutoff.getTime());
    const going = [];
    for (const file of await this.files()) {
      if (path.basename(file, '.jsonl') < oldest) {
        const text = await fsp.readFile(file, 'utf8').catch(() => '');
        if (text.includes('"kind":"quarantine"')) continue;
        going.push({ file, text });
      }
    }
    if (going.length === 0) return 0;

    /*
     * Said before it is done, and sealed (H4).
     *
     * Without this every retention pass would look exactly like somebody
     * deleting the oldest months, and the check would cry wolf once a month
     * for ever after. Written first: a record of a removal that a crash then
     * stopped is harmless -- the seals it names are still there -- while a
     * removal with no record is the very thing the check exists to report.
     */
    if (this.sealer) {
      const removed = going.map(({ file, text }) => {
        const numbers = [];
        for (const raw of text.split('\n')) {
          if (!raw.includes('"seal"')) continue;
          try {
            const line = JSON.parse(raw);
            if (line && line.op === 'seal' && Number.isInteger(line.n)) numbers.push(line.n);
          } catch {
            // not a line
          }
        }
        return { file: path.basename(file), seals: rangesOf(numbers) };
      });
      const at = this.now();
      const record = { id: `s_${crypto.randomBytes(4).toString('hex')}`, kind: null, file: this.fileFor(at), startedAt: at };
      await this._finish(record, [{ v: VERSION, t: iso(at), session: record.id, op: 'prune', removed }]);
    }

    for (const { file } of going) await fsp.rm(file, { force: true });
    return going.length;
  }

  /**
   * Every line exactly as it stands in the file, for the check (H4): its
   * text, its hash, which file and which line of it. Lines that do not parse
   * are kept too, with `line: null` -- for the check they are not noise but
   * evidence.
   *
   * @returns {Promise<{file: string, lineNo: number, index: number, text: string, hash: string, line: object|null}[]>}
   */
  async readRaw() {
    const entries = [];
    for (const file of await this.files()) {
      let text;
      try {
        text = await fsp.readFile(file, 'utf8');
      } catch {
        continue;
      }
      const name = path.basename(file);
      text.split('\n').forEach((raw, i) => {
        if (raw.trim() === '') return;
        let line = null;
        try {
          line = JSON.parse(raw);
        } catch {
          // kept as unreadable
        }
        if (!line || typeof line.session !== 'string' || typeof line.op !== 'string') line = null;
        entries.push({ file: name, lineNo: i + 1, index: entries.length, text: raw, hash: hashLine(raw), line });
      });
    }
    return entries;
  }
}

module.exports = { ActionJournal, VERSION, KEEP_MONTHS, monthOf };
