'use strict';

/**
 * The record of everything the app did to a file.
 *
 * One line of JSON per event, appended, never rewritten, in a file per month:
 *
 *   journal/2026-09.jsonl
 *   {"v":1,"t":"…","session":"s_8f2c","op":"begin","kind":"recycle","source":"manual","count":412,"bytes":…}
 *   {"v":1,"t":"…","session":"s_8f2c","op":"item","from":"C:\\…\\x.iso","to":null,"bytes":4700000000,"mtime":"…"}
 *   {"v":1,"t":"…","session":"s_8f2c","op":"end","done":410,"failed":1,"skipped":1,"movedBytes":…,"freedOnSource":0}
 *
 * ## Why append-only
 *
 * The file this replaces, `trash-ledger.json`, was rewritten whole on every
 * save from whatever copy the process had in memory. The window reads it once
 * at launch; the 02:00 cleanup is a separate process that writes to it. So a
 * window left open overnight, asked to delete something the next morning,
 * wrote back its own stale copy plus the new entries -- and the scheduled run's
 * entries were gone. Nothing broke loudly: those items were simply never
 * purged, because the record that they were ours had been overwritten.
 *
 * An append cannot lose somebody else's line. Two processes appending to the
 * same file interleave whole lines, and `scripts/test-journal.js` measures
 * that rather than assuming it.
 *
 * ## What is in a line
 *
 * An `item` line is written after the action succeeded and before the window
 * is told, so a process that dies half way leaves a journal that is exactly
 * what happened. Every destination path in it was generated by the app, never
 * read out of a file. Readers ignore fields they do not know; `prev` is
 * reserved for the hash chain the audit log (H4) will add.
 */

const crypto = require('node:crypto');
const fsp = require('node:fs/promises');
const path = require('node:path');

const { ACTION_KINDS } = require('../analyzers/contract');

const VERSION = 1;

/**
 * How long a month's file is kept. Thirteen months, so a purge grace period at
 * its maximum of a year still finds the record of what it is purging.
 */
const KEEP_MONTHS = 13;

/**
 * The kinds a session may be: the contract's actions, plus two that act on the
 * app's own earlier sessions rather than on a candidate -- the purge, which
 * removes what the app put in the bin, and the restore, which puts it back.
 * Both name each item with the moment it was first recycled (`recycledAt`),
 * which is how the ledger knows those items are no longer the app's to purge.
 */
const KINDS = new Set([...ACTION_KINDS, 'purge', 'restore']);

function monthOf(ms) {
  const d = new Date(ms);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
}

const iso = (ms) => (Number.isFinite(ms) ? new Date(ms).toISOString() : null);

class ActionJournal {
  /**
   * @param {string} dir
   * @param {object} [options]
   * @param {() => number} [options.now]   injectable clock, for the harnesses
   */
  constructor(dir, { now = Date.now, keepMonths = KEEP_MONTHS } = {}) {
    this.dir = path.resolve(dir);
    this.now = now;
    this.keepMonths = keepMonths;
    this._ready = null;
  }

  fileFor(ms) {
    return path.join(this.dir, `${monthOf(ms)}.jsonl`);
  }

  async _ensureDir() {
    if (!this._ready) this._ready = fsp.mkdir(this.dir, { recursive: true }).then(() => true);
    return this._ready;
  }

  /** One write per call, so a line is never split across two appends. */
  async _append(file, lines) {
    await this._ensureDir();
    await fsp.appendFile(file, lines.map((line) => `${JSON.stringify(line)}\n`).join(''), 'utf8');
  }

  /**
   * Open a session. Its lines all go to the file of the month it began in, so
   * a session that runs across midnight at the end of a month is still one
   * file's worth of reading.
   */
  async begin(kind, description = {}, { source = 'manual', runId = null } = {}) {
    if (!KINDS.has(kind)) throw new Error(`journal: "${kind}" is not an action kind`);
    const startedAt = this.now();
    const session = {
      id: `s_${crypto.randomBytes(4).toString('hex')}`,
      kind,
      file: this.fileFor(startedAt),
      startedAt,
    };
    await this._append(session.file, [
      {
        v: VERSION,
        t: iso(startedAt),
        session: session.id,
        op: 'begin',
        kind,
        source,
        runId,
        count: description.count || 0,
        bytes: description.bytes || 0,
        freesOnVolume: Boolean(description.freesOnVolume),
        reversible: description.reversible || null,
      },
    ]);
    return session;
  }

  /** One item that has already happened. */
  async record(session, item) {
    if (!session) return;
    await this._append(session.file, [this._itemLine(session, item)]);
  }

  _itemLine(session, item) {
    return {
      v: VERSION,
      t: iso(Number.isFinite(item.trashedAt) ? item.trashedAt : this.now()),
      session: session.id,
      op: 'item',
      // A handoff's item is what was opened -- `ms-settings:storagesense` or a
      // program with its arguments -- not a path to resolve.
      from: session.kind === 'handoff' ? String(item.path) : path.resolve(item.path),
      to: item.to || null,
      bytes: Number.isFinite(item.size) ? item.size : 0,
      mtime: iso(item.mtimeMs),
      // Only on a purge: when the item it removes was first recycled, which is
      // how the two records are matched up.
      ...(Number.isFinite(item.recycledAt) ? { recycledAt: iso(item.recycledAt) } : {}),
    };
  }

  async end(session, result = {}) {
    if (!session) return;
    await this._append(session.file, [
      {
        v: VERSION,
        t: iso(this.now()),
        session: session.id,
        op: 'end',
        done: result.done || 0,
        failed: result.failed || 0,
        skipped: result.skipped || 0,
        cancelled: Boolean(result.cancelled),
        movedBytes: result.movedBytes || 0,
        freedOnSource: result.freedOnSource || 0,
        error: result.error || null,
      },
    ]);
  }

  /**
   * A whole session in one write: for records made after the fact -- the
   * import of the old ledger, and a purge.
   */
  async appendSession(kind, items, { source = 'manual', runId = null, startedAt, freedOnSource = 0 } = {}) {
    if (!KINDS.has(kind)) throw new Error(`journal: "${kind}" is not an action kind`);
    const at = Number.isFinite(startedAt) ? startedAt : this.now();
    const session = { id: `s_${crypto.randomBytes(4).toString('hex')}`, kind, file: this.fileFor(this.now()), startedAt: at };
    const bytes = items.reduce((n, item) => n + (Number.isFinite(item.size) ? item.size : 0), 0);
    const lines = [
      { v: VERSION, t: iso(at), session: session.id, op: 'begin', kind, source, runId, count: items.length, bytes },
      ...items.map((item) => this._itemLine(session, item)),
      {
        v: VERSION,
        t: iso(this.now()),
        session: session.id,
        op: 'end',
        done: items.length,
        failed: 0,
        skipped: 0,
        cancelled: false,
        movedBytes: kind === 'purge' ? 0 : bytes,
        freedOnSource,
        error: null,
      },
    ];
    await this._append(session.file, lines);
    return session;
  }

  /** The month files present, oldest first. */
  async files() {
    let names;
    try {
      names = await fsp.readdir(this.dir);
    } catch {
      return [];
    }
    return names
      .filter((name) => /^\d{4}-\d{2}\.jsonl$/.test(name))
      .sort()
      .map((name) => path.join(this.dir, name));
  }

  /**
   * Every line, oldest file first. A line that does not parse -- a torn write
   * after a power cut, a hand edit -- is skipped and counted, never fatal: the
   * journal is read by a scheduled task that must not stop over one bad line.
   *
   * @returns {Promise<{lines: object[], malformed: number}>}
   */
  async read() {
    const lines = [];
    let malformed = 0;
    for (const file of await this.files()) {
      let text;
      try {
        text = await fsp.readFile(file, 'utf8');
      } catch {
        continue;
      }
      for (const raw of text.split('\n')) {
        if (raw.trim() === '') continue;
        let line;
        try {
          line = JSON.parse(raw);
        } catch {
          malformed += 1;
          continue;
        }
        if (!line || typeof line.session !== 'string' || typeof line.op !== 'string') {
          malformed += 1;
          continue;
        }
        lines.push(line);
      }
    }
    return { lines, malformed };
  }

  /**
   * Sessions, newest first, each with its items -- what the Restore Center
   * will list. A session with a `begin` and no `end` is reported as
   * incomplete: the process died while it was running.
   */
  async sessions() {
    const { lines } = await this.read();
    const byId = new Map();
    for (const line of lines) {
      let s = byId.get(line.session);
      if (!s) {
        s = { id: line.session, kind: null, source: null, runId: null, startedAt: null, endedAt: null, items: [], end: null };
        byId.set(line.session, s);
      }
      if (line.op === 'begin') {
        s.kind = line.kind;
        s.source = line.source || null;
        s.runId = line.runId || null;
        s.startedAt = Date.parse(line.t);
        s.count = line.count || 0;
        s.bytes = line.bytes || 0;
        s.freesOnVolume = Boolean(line.freesOnVolume);
      } else if (line.op === 'item') {
        s.items.push(line);
      } else if (line.op === 'end') {
        s.endedAt = Date.parse(line.t);
        s.end = line;
      }
    }
    return [...byId.values()]
      .filter((s) => s.kind)
      .map((s) => ({ ...s, complete: s.end !== null }))
      .sort((a, b) => b.startedAt - a.startedAt);
  }

  /**
   * Drop month files older than the retention -- this month and the twelve
   * before it, by default. Whole files only; a line is never edited.
   */
  async prune() {
    const cutoff = new Date(this.now());
    cutoff.setUTCDate(1);
    cutoff.setUTCMonth(cutoff.getUTCMonth() - (this.keepMonths - 1));
    const oldest = monthOf(cutoff.getTime());
    let removed = 0;
    for (const file of await this.files()) {
      if (path.basename(file, '.jsonl') < oldest) {
        await fsp.rm(file, { force: true });
        removed += 1;
      }
    }
    return removed;
  }
}

module.exports = { ActionJournal, VERSION, KEEP_MONTHS, monthOf };
